<?php
/**
 * Classe que implementa a estrutura FielSet do ExtJs
 *
 * @author Avanei Martendal
 * @since 17/01/2018
 */
class MensagemMail {
      private $titulo;
      private $mensagem;
      private $data;
      
      function getTitulo() {
          return $this->titulo;
      }

      function getMensagem() {
          return $this->mensagem;
      }

      function getData() {
          return $this->data;
      }

      function setTitulo($titulo) {
          $this->titulo = $titulo;
      }

      function setMensagem($mensagem) {
          $this->mensagem = $mensagem;
      }

      function setData($data) {
          $this->data = $data;
      }

            
      public function __construct($sTitulo,$sMensagem,$sData) {
          $this->titulo = $sTitulo;
          $this->mensagem = $sMensagem;
          $this->data = $sData;
      }
      
      
    
    public function getRender(){
        $sRender ='<HTML xmlns="http://www.w3.org/TR/REC-html40" xmlns:v = "urn:schemas-microsoft-com:vml" xmlns:o = "urn:schemas-microsoft-com:office:office" xmlns:w = "urn:schemas-microsoft-com:office:word" xmlns:m = "http://schemas.microsoft.com/office/2004/12/omml"><HEAD>'
                  .'<META content="text/html; charset=iso-8859-1" http-equiv=Content-Type>'
                  .'<META name=Generator content="Microsoft Word 15 (filtered medium)">'
.'<STYLE>v\: {'
.'	BEHAVIOR: url(#default#VML)'
.'}'
.'o\: {'
.'	BEHAVIOR: url(#default#VML)'
.'}'
.'w\: {'
.'	BEHAVIOR: url(#default#VML)'
.'}'
.'.shape {'
.'	BEHAVIOR: url(#default#VML)'
.'}'
.'</STYLE>'
.''
.'<STYLE>@font-face {'
.'	font-family: Helvetica;'
.'}'
.'@font-face {'
.'	font-family: Cambria Math;'
.'}'
.'@font-face {'
.'	font-family: Calibri;'
.'}'
.'@page WordSection1 {size: 612.0pt 792.0pt; margin: 70.85pt 3.0cm 70.85pt 3.0cm; }'
.'P.MsoNormal {'
.'	FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; MARGIN: 0cm 0cm 0pt; mso-fareast-language: EN-US'
.'}'
.'LI.MsoNormal {'
.'	FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; MARGIN: 0cm 0cm 0pt; mso-fareast-language: EN-US'
.'}'
.'DIV.MsoNormal {'
.'	FONT-SIZE: 11pt; FONT-FAMILY: "Calibri",sans-serif; MARGIN: 0cm 0cm 0pt; mso-fareast-language: EN-US'
.'}'
.'H3 {'
.'	FONT-SIZE: 13.5pt; FONT-FAMILY: "Times New Roman",serif; MARGIN-LEFT: 0cm; MARGIN-RIGHT: 0cm; mso-style-priority: 9; mso-style-link: "TÃ­tulo 3 Char"; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto'
.'}'
.'A:link {'
.'	TEXT-DECORATION: underline; COLOR: #0563c1; mso-style-priority: 99'
.'}'
.'SPAN.MsoHyperlink {'
.'	TEXT-DECORATION: underline; COLOR: #0563c1; mso-style-priority: 99'
.'}'
.'A:visited {'
.'	TEXT-DECORATION: underline; COLOR: #954f72; mso-style-priority: 99'
.'}'
.'SPAN.MsoHyperlinkFollowed {'
.'	TEXT-DECORATION: underline; COLOR: #954f72; mso-style-priority: 99'
.'}'
.'SPAN.Ttulo3Char {'
.'	FONT-FAMILY: "Times New Roman",serif; FONT-WEIGHT: bold; mso-fareast-language: PT-BR; mso-style-priority: 9; mso-style-link: "TÃ­tulo 3"; mso-style-name: "TÃ­tulo 3 Char"'
.'}'
.'P.msonormal0 {'
.'	FONT-SIZE: 12pt; FONT-FAMILY: "Times New Roman",serif; MARGIN-LEFT: 0cm; MARGIN-RIGHT: 0cm; mso-style-priority: 99; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-style-name: msonormal'
.'}'
.'LI.msonormal0 {'
.'	FONT-SIZE: 12pt; FONT-FAMILY: "Times New Roman",serif; MARGIN-LEFT: 0cm; MARGIN-RIGHT: 0cm; mso-style-priority: 99; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-style-name: msonormal'
.'}'
.'DIV.msonormal0 {'
.'	FONT-SIZE: 12pt; FONT-FAMILY: "Times New Roman",serif; MARGIN-LEFT: 0cm; MARGIN-RIGHT: 0cm; mso-style-priority: 99; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-style-name: msonormal'
.'}'
.'SPAN.EstiloDeEmail19 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail20 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail21 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail22 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail23 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail24 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail25 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail26 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail27 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail28 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail29 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail30 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail31 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail32 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail33 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail34 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: #1f497d; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail35 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail36 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail37 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail38 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail39 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail40 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal'
.'}'
.'SPAN.EstiloDeEmail41 {'
.'	FONT-FAMILY: "Calibri",sans-serif; COLOR: windowtext; mso-style-type: personal-reply'
.'}'
.'.MsoChpDefault {'
.'	FONT-SIZE: 10pt; mso-style-type: export-only'
.'}'
.'DIV.WordSection1 {'
.'	page: WordSection1'
.'}'
.'OL {'
.'	MARGIN-BOTTOM: 0cm'
.'}'
.'UL {'
.'	MARGIN-BOTTOM: 0cm'
.'}'
.'</STYLE>'
.'</HEAD>'
.'<BODY lang=PT-BR link=#0563c1 vLink=#954f72>'
.'<DIV class=WordSection1>'

.'<TABLE class=MsoNormalTable style="WIDTH: 100%; MARGIN-LEFT: 4.8pt; MARGIN-RIGHT: 4.8pt" cellSpacing=0 cellPadding=0 width="100%" align=left border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="WIDTH: 100%; BACKGROUND: #f1f2f7; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm" vAlign=top width="100%">'
.'<br/><br/>'
                
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable style="WIDTH: 450pt" cellSpacing=0 cellPadding=0 width=600 border=0>'
.'<TBODY>'
.'<TR style="HEIGHT: 11.25pt">'
.'<TD style="HEIGHT: 11.25pt; BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR>'
.'<TR>'
.'<TD style="BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable style="WIDTH: 420pt" cellSpacing=0 cellPadding=0 width=560 border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<TABLE class=MsoNormalTable cellSpacing=0 cellPadding=0 align=left border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable cellSpacing=0 cellPadding=0 border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style=\'FONT-SIZE: 6.5pt; FONT-FAMILY: "Helvetica",sans-serif; COLOR: white\'>METALBO INDUSTRIA DE FIXADORES METALICOS LTDA '.$this->getData().'<o:p></o:p></SPAN></P></TD></TR>'
.'</TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif; DISPLAY: none"><o:p>&nbsp;</o:p></SPAN></P>'
.'<TABLE class=MsoNormalTable cellSpacing=0 cellPadding=0 align=left border=0>'
.'<TBODY>'
.'<TR style="HEIGHT: 15pt">'
.'<TD style="HEIGHT: 15pt; WIDTH: 22.5pt; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm" width=30></TD></TR></TBODY></TABLE>'
.'<TABLE class=MsoNormalTable cellSpacing=0 cellPadding=0 align=right border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable cellSpacing=0 cellPadding=0 border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P></TD>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif">&nbsp;&nbsp;<o:p></o:p></SPAN></P></TD>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style=\'FONT-SIZE: 8.5pt; FONT-FAMILY: "Helvetica",sans-serif; COLOR: #fefefe\'><o:p></o:p></SPAN></P></TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 12pt; FONT-FAMILY: "Times New Roman",serif; mso-fareast-language: PT-BR"><o:p></o:p></SPAN></P></TD></TR></TBODY></TABLE></DIV></TD></TR>'
.'<TR style="HEIGHT: 7.5pt">'
.'<TD style="HEIGHT: 7.5pt; BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR>'
.'<TR>'
.'<TD style="BACKGROUND: white; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable style="WIDTH: 420pt" cellSpacing=0 cellPadding=0 width=560 border=0>'
.'<TBODY>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR>'
.'<TR style="HEIGHT: 15pt">'
.'<TD style="HEIGHT: 15pt; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable style="WIDTH: 396pt" cellSpacing=0 cellPadding=0 width=528 border=0>'
.'<TBODY>'
.'    '
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<H3 style="MARGIN-BOTTOM: 13.5pt; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style=\'FONT-SIZE: 14pt; FONT-FAMILY: "Helvetica",sans-serif\'>'.$this->getTitulo().'<o:p></o:p></SPAN></SPAN></H3>'
.'<P class=MsoNormal style=\'mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly\'>'.$this->getMensagem().'<o:p></o:p></P>'
.'</TD>'
.'</TR>'
.'<TR>'
.'<TD style="PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'</TR>'
.'</TBODY>'
.'</TABLE></DIV></TD></TR>'
.'<TR style="HEIGHT: 18.75pt">'
.'<TD style="HEIGHT: 18.75pt; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR></TBODY></TABLE></DIV></TD></TR>'
.'<TR>'
.'<TD style="BACKGROUND: white; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><o:p>&nbsp;</o:p></P>'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style="COLOR: #1f497d; mso-fareast-language: PT-BR"><IMG id=_x0000_i1025 style="HEIGHT: 0.479in; WIDTH: 1.541in" border=0 alt=cid:image001.png src="http://metalbo.com.br/img/logo/logoPng.png" width=148 height=46></SPAN><SPAN style="COLOR: #1f497d"><o:p></o:p></SPAN></P></TD></TR>'
.'<TR style="HEIGHT: 22.5pt">'
.'<TD style="HEIGHT: 22.5pt; BACKGROUND: white; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR></TBODY></TABLE></DIV>'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif; DISPLAY: none"><o:p>&nbsp;</o:p></SPAN></P>'
.'<DIV align=center>'
.'<TABLE class=MsoNormalTable style="WIDTH: 450pt" cellSpacing=0 cellPadding=0 width=600 border=0>'
.'<TBODY>'
.'<TR style="HEIGHT: 11.25pt">'
.'<TD style="HEIGHT: 11.25pt; BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR>'
.'<TR>'
.'<TD style="BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm">'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style=\'FONT-SIZE: 6.5pt; FONT-FAMILY: "Helvetica",sans-serif; COLOR: white\'>Metalbo Copyright 2018. <o:p></o:p></SPAN></P></TD></TR>'
.'<TR style="HEIGHT: 10.5pt">'
.'<TD style="HEIGHT: 10.5pt; BACKGROUND: #256541; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR></TBODY></TABLE></DIV>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly"><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style="FONT-SIZE: 10.5pt; FONT-FAMILY: "Arial",sans-serif; COLOR: #1f497d"><o:p>&nbsp;</o:p></SPAN></P>'
.'<P class=MsoNormal style="TEXT-ALIGN: center; mso-element: frame; mso-element-frame-hspace: 7.05pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: column; mso-height-rule: exactly" align=center><SPAN style="COLOR: #1f497d"><o:p>&nbsp;</o:p></SPAN></P></TD></TR>'
.'<TR style="HEIGHT: 22.5pt">'
.'<TD style="HEIGHT: 22.5pt; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 0cm; PADDING-RIGHT: 0cm"></TD></TR></TBODY></TABLE>'
.'<P class=MsoNormal><o:p>&nbsp;</o:p></P>'
.'<P class=MsoNormal><o:p>&nbsp;</o:p></P>'
.'<P class=MsoNormal><o:p>&nbsp;</o:p></P>'
.'<P class=MsoNormal><SPAN style="COLOR: #1f497d"><o:p>&nbsp;</o:p>'
.'</SPAN>'
.'</P>'
.'</DIV>'
.'</BODY>'
.'</HTML>';
        
return $sRender;
    }
      
      
}
?>
